---
wod20skills:
  advantages_cost: 2
  allow_incapable_action_skills: false
  free_backgrounds: 5
  free_languages: 1
  max_ap: 40
  max_attr_rating: 5
  max_attrs_at_or_above:
    '5': 12
  max_points_on_action: 28
  max_points_on_advantages: 12
  max_points_on_attrs: 12
  max_skill_rating: 5
  max_skills_at_or_above:
    '5': 0
  min_backgrounds: 2
  starting_skills:
    Everyone:
      skills:
    Position:
  unusual_skills:
